export const pricingPlans = [
  {
    name: "Starter",
    price: "750 TL",
    period: "/ay",
    description: "İçerik fikirlerini keşfet, ilk adımı at",
    features: [
      "Yorum cevap verme otomasyonu",
      "İçerik havuzuna erişim",
      "Ayda 3 video skor analizi",
      "Temel profil analiz raporu",
      "E-posta desteği",
    ],
    cta: "Hemen Başla",
    highlighted: false,
  },
  {
    name: "Profesyonel",
    price: "1150 TL",
    period: "/ay",
    description: "Tam paket: içerikten analize her şey dahil",
    features: [
      "Yorum cevap verme otomasyonu",
      "DM otomasyonu",
      "Sınırsız içerik havuzu erişimi",
      "Popüler video analiz raporları",
      "Diyalog ve senaryo hazırlama",
      "Sınırsız video skor analizi",
      "Detaylı profil analizi ve öneriler",
      "Öncelikli WhatsApp desteği",
    ],
    cta: "En Popüler Paketi Seç",
    highlighted: true,
  },
  {
    name: "Ajans",
    price: "1500 TL",
    period: "/ay",
    description: "Markalar ve profesyonel içerik üreticileri için",
    features: [
      "Yorum cevap verme otomasyonu",
      
      "DM otomasyonu",
      "Chat AI bot",
      "Profesyonel paketteki her şey",
      "Birden fazla hesap yönetimi",
      "Özel içerik stratejisi toplantıları",
      "Haftalık performans raporları",
      "Özel danışmanlık hattı",
      "Rakip analiz raporları",
    ],
    cta: "Hemen Başla",
    highlighted: false,
  },
];
